### ISSUE TITLE
Help with browser

### ISSUE THREAD

**Issue by deicidemilan** [krasimir/webpack-library-starter#55] opened 2020-12-04 13:22 UTC
Hi, I try this, and work in test. But can I get this work inside browser.
If I import in html I got error in browser:

`import {Dog} from './lib/webpack-library-starter.min.js';
const dog = new Dog();
Dog.name;

> Uncaught SyntaxError: The requested module './lib/webpack-library-starter.min.js' does not provide an export named 'Dog'

**Comment by krasimir** [comment] 2020-12-19 14:03
I just updated the starter to the latest webpack and babel. Can you try again. 

What I just tested is the following [node.js](https://github.com/krasimir/webpack-library-starter/blob/master/lib/node.js) file:

```js
import { Dog } from "./webpack-library-starter";

const d = new Dog();
console.log(d.name);
```

I transpiled it with ` ./node_modules/.bin/babel ./lib/node.js -o ./lib/node.transpiled.js` and the transpiled version [node.transpiled.js](https://github.com/krasimir/webpack-library-starter/blob/master/lib/node.transpiled.js) looks like this:

```js
"use strict";

var _webpackLibraryStarter = require("./webpack-library-starter");

var d = new _webpackLibraryStarter.Dog();
console.log(d.name);
```

When I run it with node via `node ./lib/node.transpiled.js` I'm getting:

```js
> node ./lib/node.transpiled.js
Hello world from the bundle!
Dog
```

Which is the expected behavior. 

I'll close this issue. Let me know if you still have problems.

**Closed as completed by krasimir** 2020-12-19 14:03 UTC
